# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âžœ'
#success_symbol = '[ó°Š• =>](bold green)' # The 'success_symbol' segment is being set to 'âžœ' with the color 'bold green'

[username]
style_root = "red bold"
format = "ðŸ¦Š [$user](bold green) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
trim_at = "."
disabled = false

[character]
success_symbol = " [>](bold green)"
error_symbol = " [x](bold red)"
vimcmd_symbol = " [<](bold green)"


[git_branch]
symbol = "ðŸŒ¿ "
style = "bold cyan"

[git_status]
stashed = "ðŸ“¦ "
ahead = "ðŸš€ "
diverged = "âš¡"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
symbol = "ðŸ "
style = "bold blue"

[nodejs]
symbol = "ðŸŸ© "
style = "bold green"

[ruby]
symbol = "ðŸ’Ž "
style = "bold red"

[rust]
symbol = "ðŸ¦€ "
style = "bold orange"

